<?php include('includes/head_services.php'); ?>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
		<?php include_once("analyticstracking.php") ?>

        <?php include('includes/nav_services.php'); ?>

        <div class="container">

			<div class="main_content">
			<!-- Example row of columns -->
            <div class="row animated fadeInLeft">
                <?php include('includes/sidebar_nav_services.php'); ?>
				<div class="span8 margin_main_container">
					<div class="title_bkgd">
						<h1>Continuous Optimization</h1>
					</div>
					<img src="img/services/continuousoptmain.png" class="main_picture" alt="Continuous Optimization Main Picture">
					<p>
						Continuous optimization addresses changes in facility occupancy, use, maintenance and repair. 
						Periodic adjustments and reviews of building operating systems and procedures are essential for optimal energy 
						efficiency and service provision. Continuous optimization is a dynamic process intended to facilitate the efficient 
						operation of a previously commissioned building. It repeats many elements of the standard commissioning process over a 
						longer time period and should shorten the time intervals between operation and equipment reviews.<br>
						<br>
						Continuous optimization incorporates the monitoring and analysis of building performance data generated by the 
						building automation system, or other permanently installed metering equipment, to verify high-level building performance, 
						occupant satisfaction, and the financial outcomes of capital investments.<br>
						<br>
						Continuous optimization is distinct from preventive maintenance. While preventive maintenance focuses on the individual 
						equipment or building sub-system maintenance tasks continuous optimization emphasizes systems-wide approach 
						making sure building systems operation are understood, monitored and optimized. 
					</p>
                </div>
            </div>	
			</div>
			

            <?php include('includes/footer.php'); ?>

</div> <!-- /container -->

<?php include('includes/js.php'); ?>
    </body>
</html>
